# Generated by Django 4.2.1 on 2023-06-19 11:47

from django.conf import settings
import os
from django.db import migrations


def initialize_users(apps, schema_editor):
    from django.core.management import call_command

    call_command(
        "loaddata",
        os.path.join(settings.BASE_DIR, "demo", "fixtures", "users.json"),
        verbosity=0,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0002_paymentterm"),
    ]

    operations = [migrations.RunPython(initialize_users)]
