name: Deploy demo

on: workflow_dispatch

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_KEY }}

jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy demo to https://django-crispy-formset-modal.fly.dev/
      run: flyctl deploy --remote-only
